[2025-05-28T21:08:01.488+0200] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: backfill_pollution_weather_dag.fetch_full_history_all_cities manual__2025-05-28T19:07:58.386102+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
