[2025-06-08T23:50:26.139+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T23:50:26.155+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: backfill_pollution_weather_dag.format_backfill_all_data manual__2025-06-08T21:50:23.298679+00:00 [queued]>
[2025-06-08T23:50:26.158+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: backfill_pollution_weather_dag.format_backfill_all_data manual__2025-06-08T21:50:23.298679+00:00 [queued]>
[2025-06-08T23:50:26.158+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 2
[2025-06-08T23:50:26.174+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): format_backfill_all_data> on 2025-06-08 21:50:23.298679+00:00
[2025-06-08T23:50:26.176+0200] {standard_task_runner.py:63} INFO - Started process 1211921 to run task
[2025-06-08T23:50:26.178+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'backfill_pollution_weather_dag', 'format_backfill_all_data', 'manual__2025-06-08T21:50:23.298679+00:00', '--job-id', '315', '--raw', '--subdir', 'DAGS_FOLDER/backfill_dag.py', '--cfg-path', '/tmp/tmpsthoh_0b']
[2025-06-08T23:50:26.178+0200] {standard_task_runner.py:91} INFO - Job 315: Subtask format_backfill_all_data
[2025-06-08T23:50:26.208+0200] {task_command.py:426} INFO - Running <TaskInstance: backfill_pollution_weather_dag.format_backfill_all_data manual__2025-06-08T21:50:23.298679+00:00 [running]> on host DESKTOP-2QS8J6D.
[2025-06-08T23:50:26.266+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='backfill_pollution_weather_dag' AIRFLOW_CTX_TASK_ID='format_backfill_all_data' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T21:50:23.298679+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T21:50:23.298679+00:00'
[2025-06-08T23:50:26.267+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T23:50:26.577+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T23:50:26.579+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ccd/airflow/dags/backfill_dag.py", line 156, in format_backfill_all_dates
    spark = SparkSession.builder.appName("BackfillFormat").master("local[*]").getOrCreate()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/sql/session.py", line 556, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 523, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 205, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 444, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/java_gateway.py", line 111, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-06-08T23:50:26.583+0200] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=backfill_pollution_weather_dag, task_id=format_backfill_all_data, execution_date=20250608T215023, start_date=20250608T215026, end_date=20250608T215026
[2025-06-08T23:50:26.600+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 315 for task format_backfill_all_data ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 1211921)
[2025-06-08T23:50:26.633+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T23:50:26.641+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T23:50:26.641+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
