[2025-06-08T13:31:48.901+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T13:31:48.914+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: backfill_pollution_weather_dag.format_pollution_backfill manual__2025-06-08T11:28:01.524862+00:00 [queued]>
[2025-06-08T13:31:48.917+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: backfill_pollution_weather_dag.format_pollution_backfill manual__2025-06-08T11:28:01.524862+00:00 [queued]>
[2025-06-08T13:31:48.917+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-06-08T13:31:48.934+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): format_pollution_backfill> on 2025-06-08 11:28:01.524862+00:00
[2025-06-08T13:31:48.937+0200] {standard_task_runner.py:63} INFO - Started process 9749 to run task
[2025-06-08T13:31:48.941+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'backfill_pollution_weather_dag', 'format_pollution_backfill', 'manual__2025-06-08T11:28:01.524862+00:00', '--job-id', '206', '--raw', '--subdir', 'DAGS_FOLDER/backfill_dag.py', '--cfg-path', '/tmp/tmpfdnozo7d']
[2025-06-08T13:31:48.941+0200] {standard_task_runner.py:91} INFO - Job 206: Subtask format_pollution_backfill
[2025-06-08T13:31:48.973+0200] {task_command.py:426} INFO - Running <TaskInstance: backfill_pollution_weather_dag.format_pollution_backfill manual__2025-06-08T11:28:01.524862+00:00 [running]> on host DESKTOP-2QS8J6D.
[2025-06-08T13:31:49.031+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='backfill_pollution_weather_dag' AIRFLOW_CTX_TASK_ID='format_pollution_backfill' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T11:28:01.524862+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T11:28:01.524862+00:00'
[2025-06-08T13:31:49.032+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T13:31:49.645+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T13:31:49.645+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ccd/airflow/dags/backfill_dag.py", line 120, in format_pollution_backfill
    spark = SparkSession.builder.appName("FormatBackfillPollution").master("local[*]").getOrCreate()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/sql/session.py", line 556, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 523, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 205, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 444, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/java_gateway.py", line 111, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-06-08T13:31:49.649+0200] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=backfill_pollution_weather_dag, task_id=format_pollution_backfill, execution_date=20250608T112801, start_date=20250608T113148, end_date=20250608T113149
[2025-06-08T13:31:49.729+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 206 for task format_pollution_backfill ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 9749)
[2025-06-08T13:31:49.756+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T13:31:49.768+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T13:31:49.784+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
