[2025-06-08T13:41:05.797+0200] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-08T13:41:05.814+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_spark_connection.test_spark_session manual__2025-06-08T11:41:03.062329+00:00 [queued]>
[2025-06-08T13:41:05.817+0200] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_spark_connection.test_spark_session manual__2025-06-08T11:41:03.062329+00:00 [queued]>
[2025-06-08T13:41:05.817+0200] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-06-08T13:41:05.832+0200] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): test_spark_session> on 2025-06-08 11:41:03.062329+00:00
[2025-06-08T13:41:05.834+0200] {standard_task_runner.py:63} INFO - Started process 12433 to run task
[2025-06-08T13:41:05.837+0200] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'test_spark_connection', 'test_spark_session', 'manual__2025-06-08T11:41:03.062329+00:00', '--job-id', '213', '--raw', '--subdir', 'DAGS_FOLDER/test_spark.py', '--cfg-path', '/tmp/tmpi6ed921k']
[2025-06-08T13:41:05.839+0200] {standard_task_runner.py:91} INFO - Job 213: Subtask test_spark_session
[2025-06-08T13:41:05.868+0200] {task_command.py:426} INFO - Running <TaskInstance: test_spark_connection.test_spark_session manual__2025-06-08T11:41:03.062329+00:00 [running]> on host DESKTOP-2QS8J6D.
[2025-06-08T13:41:05.931+0200] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test_spark_connection' AIRFLOW_CTX_TASK_ID='test_spark_session' AIRFLOW_CTX_EXECUTION_DATE='2025-06-08T11:41:03.062329+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-08T11:41:03.062329+00:00'
[2025-06-08T13:41:05.932+0200] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-08T13:41:05.933+0200] {logging_mixin.py:188} INFO - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
[2025-06-08T13:41:06.241+0200] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-08T13:41:06.241+0200] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ccd/airflow/dags/test_spark.py", line 14, in test_spark
    .getOrCreate()
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/sql/session.py", line 556, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 523, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 205, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/core/context.py", line 444, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/ccd/airflow_venv/lib/python3.10/site-packages/pyspark/java_gateway.py", line 111, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-06-08T13:41:06.244+0200] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=test_spark_connection, task_id=test_spark_session, execution_date=20250608T114103, start_date=20250608T114105, end_date=20250608T114106
[2025-06-08T13:41:06.261+0200] {standard_task_runner.py:110} ERROR - Failed to execute job 213 for task test_spark_session ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 12433)
[2025-06-08T13:41:06.291+0200] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-08T13:41:06.298+0200] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-08T13:41:06.299+0200] {local_task_job_runner.py:222} INFO - ::endgroup::
